export const COST_CATEGORIES = [
    'Bou DPS',
    'Gold Savings',
    'Tour Savings',
    '5% Freelancing Savings',
    'Eidul Fitr',
    'Shashuri',
    'Ammu',
    'Bou',
    'Kobutor Cost',
    'Freelancing Cost',
    'Freelancing Setup',
    'Market place Cost',
    'Rent',
    'Gas',
    'Electricity Bill',
    'Water Supply',
    'Mobile Bill',
    'Internet',
    'Education',
    'Treatment',
    'Transport',
    'Vegetable',
    'Rice',
    'Piaj',
    'Rosun',
    'Polau Rice',
    'Dal',
    'Salt',
    'Alu',
    'Fruits',
    'Snacks',
    'toiletries',
    'Egg',
    'Milk',
    'Modhu',
    'Chola',
    'Muri',
    'Spaces',
    'Sugar',
    'Tea',
    'Meat',
    'Fish',
    'Oil',
    'Ata',
    'Personal Care',
    'Home',
    'Others',
    'Home tour',
    'Charity/Mosque',
    'Roja',
    'Tour',
    'Others Festival',
    'Eidul Adha',
    'Zakat',
    'Maintenance/Charge',
    'Office Program',
    'Tasmim',
    'Ayman',
    'Sajid',
    'Costume',
    'Tailor Machine',
    'Backup UPS',
    'Book Shelf 2',
    'Passport',
    'Table',
    'Showcase',
    'Dressing Table',
    'Rack',
    'TV',
    'Motor Cycle',
    'Kitchen',
    'Mobile Me',
    'Mobile Bou',
    'Mobile Ammu',
    'Oven',
    'Loan Khala',
    'Loan Himel',
    'Loan M Ali',
    'Loan Ammu',
    'Loan Dolil',
    'Current Loan Payment',
    'Uncertinity'
];

export const INCOME_SOURCES = [
    'Jannat',
    'Freelancing',
    'farm',
    'Loan',
    'Opening Balance',
    'Others'
];
